# https://github.com/esphome/home-assistant-voice-pe/blob/8178e25aceb4f08b0f2e932dc902974dc7f1632a/home-assistant-voice.yaml
esphome:
  name: mrassistant
  friendly_name: "Mr Assistant"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Mrassistant Fallback Hotspot"
    password: "Cim4W4fjWQ6H"

captive_portal:

# I2S Audio configuration  
i2s_audio:
  - id: i2s_input
    # data line is GPIO11
    i2s_lrclk_pin:
      number: GPIO09
    i2s_bclk_pin:
      number: GPIO10

  - id: i2s_output
    # i2s_output data pin is GPIO07
    i2s_lrclk_pin:
      number: GPIO5
    i2s_bclk_pin:
      number: GPIO6

# Microphone configuration  
microphone:
  - platform: i2s_audio
    id: mic
    i2s_audio_id: i2s_input
    i2s_din_pin: GPIO11
    adc_type: external
    sample_rate: 16000
    bits_per_sample: 32bit
    channel: left

# Speaker configuration
speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: i2s_output
    i2s_dout_pin: GPIO07
    bits_per_sample: 32bit
    dac_type: external
    channel: mono
    timeout: never
    sample_rate: 48000
    buffer_duration: 100ms

# Wake word detection
micro_wake_word:
  id: mww
  models:
    - model: okay_nabu
  microphone:
    microphone: mic
    channels: 0
    gain_factor: 4
  stop_after_detection: false
  vad:
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;

# Voice assistant configuration
voice_assistant:
  microphone:
    microphone: mic
    channels: 0
  speaker: speaker_id
  noise_suppression_level: 0
  auto_gain: 0 dbfs
  volume_multiplier: 1
  micro_wake_word: mww
  use_wake_word: false
  
  on_client_connected:
    - micro_wake_word.start:
        
  on_client_disconnected:
    - voice_assistant.stop:

  on_start:
    - logger.log: "Voice assistant started"
  
  on_wake_word_detected:
    - logger.log: "Wake word detected by voice assistant"
  
  on_stt_vad_end:
    - logger.log: "Speech ended"
  
  on_tts_start:
    - logger.log: "TTS started"
  
  on_tts_end:
    - logger.log: "TTS ended"
  
  on_end:
    - logger.log: "Voice assistant ended"
  
  on_error:
    - logger.log: "Voice assistant error"