esphome:
  name: esp32-audio-dac
  friendly_name: "ESP32 Audio DAC"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: "your-ota-password-here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Audio-Dac Fallback Hotspot"
    password: "fallback-password"

captive_portal:

# I2S Audio Configuration
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO15    # Word Select (WS) - Frame sync
    i2s_bclk_pin: GPIO16     # Bit Clock (BCK) - Serial clock

# Media Player Component
media_player:
  - platform: i2s_audio
    id: media_out
    name: "ESP32 I2S Audio"
    dac_type: external
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO17     # Data Out (DIN on DAC)
    mode: stereo