esphome:
  name: mic-speaker-test
  friendly_name: "Mic Speaker Test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

logger:
  level: INFO

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Mic-Speaker-Test"
    password: "TestPassword"

captive_portal:

# I2S Audio
i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO16

# INMP441 Microphone
microphone:
  - platform: i2s_audio
    id: mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO18
    adc_type: external
    pdm: false
    bits_per_sample: 32bit
    channel: left

# MAX98357A Speaker
speaker:
  - platform: i2s_audio
    id: speaker_out
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO17
    dac_type: external
    channel: mono

# Voice Assistant for record/playback
voice_assistant:
  microphone: mic
  speaker: speaker_out
  on_listening:
    - logger.log: "Recording... speak now!"
  on_stt_end:
    - logger.log: "Playback starting..."
  on_tts_end:
    - logger.log: "Test complete!"
  on_error:
    - logger.log: "Error in mic/speaker test"

# Test button
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Test Mic & Speaker"
    on_press:
      - logger.log: "Starting mic/speaker test..."
      - voice_assistant.start: