esphome:
  name: i2s_dac_test
  friendly_name: I2S DAC Test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "I2S DAC Test Fallback"
    password: "fallback_password"

captive_portal:

# I2S Audio interface
i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO16

# Define speaker connected to external DAC
speaker:
  - platform: i2s_audio
    id: dac_speaker
    dac_type: external
    i2s_dout_pin: GPIO17
    channel: mono

# Create a media player using the speaker
media_player:
  - platform: speaker
    name: "ESP32 I2S DAC Speaker"
    announcement_pipeline:
      speaker: dac_speaker
    # speaker_id: dac_speaker
